sam2_checkpoint: 'checkpoints/sam2.1_hiera_large.pt'
model_cfg: 'configs/sam2.1/sam2.1_hiera_l.yaml'
  # sam2_checkpoint: 'checkpoints/sam2.1_hiera_tiny.pt'
  # model_cfg: 'configs/sam2.1/sam2.1_hiera_t.yaml'